target 'iOS-Tests' do
  platform :ios, '5.0'
  pod 'OMPromises/HTTP', :path => '../'
end

target 'OSX-Tests' do
  platform :osx, '10.7'
  pod 'OMPromises/HTTP', :path => '../'
end

target 'tvOS-Tests' do
  platform :tvos, '9.0'
  pod 'OMPromises/HTTP', :path => '../'
end
