target :ios do
  platform :ios, '5.0'
  link_with 'iOS-Tests'
  pod 'OMPromises/HTTP', :path => '../../'
end

target :osx do
  platform :osx, '10.7'
  link_with 'OS-X-Tests'
  pod 'OMPromises/HTTP', :path => '../../'
end
